---
- Nobody knows for certain.
- Unknown.
- Unknowable.
- Because.
- Why not?
- The alignment of the planets caused that.
- Quantum entanglement.
- "Because #{deity} wills it"
- Have you tried staring really, really hard at it?
- Have you tried deleting it all and starting again?
- Code has gained sentience.
- Ambient temperature not at recommended levels.
- Sun at incorrect angle.
- Moon at incorrect angle.
- Computer too far to the left.
- Computer too far to the right.
- Computer too high.
- Computer too low.
- Computer in unknown n-dimensional space.
- 42.
- Because I said so.
- I read it on the Internet.
- "It's on a need-to-know basis. You don't need to know"
- "Because on R'lyeh, they don't accept American Express."
