nick: logga
channels:
  - "#logga"
  - "#rubyonrails"
  - "#railsbridge"
  - "#spree"
  - "#spree-dev"
  - "#Rubyonrails-offtopic"
  - "#ruby"
auto_rejoin: true
database:
  adapter: postgresql
  database: gitpilot