nick: logga
channels:
  - "#logga"
  - "#rubyonrails"
  - "#railsbridge"
  - "#spree"
  - "#spree-dev"
  - "#Rubyonrails-offtopic"
  - "#ruby"
owner: "radar"
authorized_users:
  -"radar"
  -"workmad3"
  -"toretore"
  -"augustl"
  -"Remear"
  -"SuperTaz"
  -"eladmeidar"
  -"ReinH"
  -"Hates_"
  -"JayM"
  -"mark[oz]"
  -"anathematic"
  -"pjammer"
  -"confounds"
  -"dpickett"
  -"camonz"
  -"crankharder"
  -"fowlduck"
  -"Derander"
  -"tobago"
  -"bjeanes"
  -"omarqureshi"
  -"wmoxam"
  -"dfr | work"
  -"kithpom"
  -"jschoolcraft"
  -"Dreamer3"
  -"philcrissman"
  -"halogenandtoast"
  -"edavis10"
  -"withanx"
  -"leethal"
  -"djones"
  -"djones_"
  -"wycats"
  -"apow"
  -"wuputah"
  -"jasonking"
  -"dfr"
  -"m4rtijn | lap"
  -"rsl"
  -"hates"
  -"lenary"
  -"apeiros_"
  -"Caius"
  -"foucist"
  -"magneto"
  -"xanderbeedle"
  -"RubyPanther"
  -"rds"
  -"nate-"
  -"zodiak"
  -"apeiros"
  -"rohit"
  -"hosh_work"
  -"Tass_"
  -"erikh"
  -"twe4ked"
  -"Tasser"
  -"aperios_"
  -"aperios"
  -"SpaceGhostC2C"
  -"samuelkadolph"
auto_rejoin: true
database:
  adapter: postgresql
  database: gitpilot